INSERT INTO MONEDA(ID, NOMBRE , SIMBOLO, FLG_ACTIVO, ID_USUARIO_MODIF, FEC_USUARIO_MODIF) 
VALUES (1, 'SOLES', 'S/', 1, 1, now());

INSERT INTO TIPO_CAMBIO(ID, ID_MONEDA , VALOR_COMPRA, VALOR_VENTA, FLG_ACTIVO, ID_USUARIO_MODIF, FEC_USUARIO_MODIF) 
VALUES (1, 1, 1.00, 1.00, 1, 1, now());
