CREATE TABLE IF NOT EXISTS MONEDA (
  ID SERIAL PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(250) NOT NULL,
  SIMBOLO VARCHAR(50) NOT NULL,
  FLG_ACTIVO INTEGER NOT NULL,
  ID_USUARIO_MODIF INTEGER NULL,
  FEC_USUARIO_MODIF DATE NULL
);

CREATE TABLE IF NOT EXISTS TIPO_CAMBIO (
  ID SERIAL PRIMARY KEY NOT NULL,
  ID_MONEDA INTEGER NOT NULL,
  VALOR_COMPRA NUMERIC(8,2) NOT NULL,
  VALOR_VENTA NUMERIC(8,2) NOT NULL,
  FLG_ACTIVO INTEGER NOT NULL,
  ID_USUARIO_MODIF INTEGER NULL,
  FEC_USUARIO_MODIF DATE NULL,
  FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID)
);


CREATE TABLE IF NOT EXISTS CAMBIO (
  ID SERIAL PRIMARY KEY NOT NULL,
  MONTO NUMERIC(8,2) NOT NULL,
  ID_MONEDA_ORIG INTEGER NOT NULL,
  ID_MONEDA_DEST INTEGER NOT NULL,
  MONTO_EQUIVAL NUMERIC(8,2) NOT NULL,
  FLG_ACTIVO INTEGER NOT NULL,
  ID_USUARIO_MODIF INTEGER NULL,
  FEC_USUARIO_MODIF DATE NULL
);